"""create_medicacao_table

Revision ID: 0d7c49c38725
Revises: fa36d9f4c0b6
Create Date: 2026-02-03 18:53:23.377814

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '0d7c49c38725'
down_revision: Union[str, Sequence[str], None] = 'fa36d9f4c0b6'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('medicacoes',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('nome', sa.String(), nullable=False),
    sa.Column('dosagem', sa.String(), nullable=False),
    sa.Column('frequencia', sa.String(), nullable=False),
    sa.Column('paciente_id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['paciente_id'], ['pacientes.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('pacientes') as batch_op:
        batch_op.alter_column('data_nascimento',
                   existing_type=sa.DATETIME(),
                   nullable=False)
        batch_op.alter_column('sexo',
                   existing_type=sa.VARCHAR(length=50),
                   nullable=False)
        batch_op.alter_column('data_diagnostico',
                   existing_type=sa.DATETIME(),
                   nullable=False)
        batch_op.drop_column('medicacoes')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('pacientes') as batch_op:
        batch_op.add_column(sa.Column('medicacoes', sa.TEXT(), nullable=True))
        batch_op.alter_column('data_diagnostico',
                   existing_type=sa.DATETIME(),
                   nullable=True)
        batch_op.alter_column('sexo',
                   existing_type=sa.VARCHAR(length=50),
                   nullable=True)
        batch_op.alter_column('data_nascimento',
                   existing_type=sa.DATETIME(),
                   nullable=True)
    op.drop_table('medicacoes')
    # ### end Alembic commands ###
