"""create all tables

Revision ID: 2dd3ae881459
Revises: 1ba80f7b0e8d
Create Date: 2026-01-26 19:49:23.670003

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '2dd3ae881459'
down_revision: Union[str, Sequence[str], None] = '1ba80f7b0e8d'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('alertas',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('tipo', sa.String(), nullable=False),
    sa.Column('data_hora', sa.DateTime(), nullable=False),
    sa.Column('paciente_id', sa.Integer(), nullable=False),
    sa.Column('descricao', sa.Text(), nullable=False),
    sa.Column('ativo', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['paciente_id'], ['pacientes.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('contatos_apoio',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('nome', sa.String(), nullable=False),
    sa.Column('email', sa.String(), nullable=False),
    sa.Column('telefone', sa.String(), nullable=False),
    sa.Column('parentesco', sa.String(), nullable=False),
    sa.Column('paciente_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['paciente_id'], ['pacientes.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('registros',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('tipo_registro', sa.String(), nullable=False),
    sa.Column('paciente_id', sa.Integer(), nullable=False),
    sa.Column('data_hora', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['paciente_id'], ['pacientes.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('registros_crises',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('intensidade_dor', sa.Integer(), nullable=False),
    sa.Column('duracao', sa.String(), nullable=False),
    sa.Column('audio_path', sa.String(), nullable=True),
    sa.Column('texto_transcrito', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['id'], ['registros.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('registros_diarios',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('intensidade_dor', sa.Integer(), nullable=False),
    sa.Column('qualidade_sono', sa.Integer(), nullable=False),
    sa.Column('nivel_fadiga', sa.Integer(), nullable=False),
    sa.Column('estado_emocional', sa.Enum('FELIZ', 'ANSIOSO', 'IRRITADO', 'TRISTE', name='estadoemocional'), nullable=False),
    sa.Column('localizacao_dor', sa.String(), nullable=True),
    sa.ForeignKeyConstraint(['id'], ['registros.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.add_column('pacientes', sa.Column('data_nascimento', sa.DateTime(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('pacientes', 'data_nascimento')
    op.drop_table('registros_diarios')
    op.drop_table('registros_crises')
    op.drop_table('registros')
    op.drop_table('contatos_apoio')
    op.drop_table('alertas')
    # ### end Alembic commands ###
