"""add email password and updated_at to pacientes

Revision ID: 35b3a959c514
Revises: 9cdcf4a9a285
Create Date: 2026-01-26 13:59:02.452388

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '35b3a959c514'
down_revision: Union[str, Sequence[str], None] = '9cdcf4a9a285'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('pacientes', schema=None) as batch_op:
        batch_op.add_column(sa.Column('email', sa.String(), nullable=False))
        batch_op.add_column(sa.Column('password', sa.String(), nullable=False))
        batch_op.add_column(sa.Column('updated_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False))
        batch_op.create_unique_constraint('uq_pacientes_email', ['email'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('pacientes', schema=None) as batch_op:
        batch_op.drop_constraint('uq_pacientes_email', type_='unique')
        batch_op.drop_column('updated_at')
        batch_op.drop_column('password')
        batch_op.drop_column('email')
    # ### end Alembic commands ###
