"""refactor_registro_diario_and_add_sintomas_regioes

Revision ID: 429d5bedb7e9
Revises: 50d3ad34ecec
Create Date: 2026-02-07 15:54:36.615874

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '429d5bedb7e9'
down_revision: Union[str, Sequence[str], None] = '50d3ad34ecec'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('registro_regioes_dor',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('registro_id', sa.Integer(), nullable=False),
    sa.Column('regiao_id', sa.String(length=10), nullable=False),
    sa.Column('intensidade', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['registro_id'], ['registros_diarios.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('registro_sintomas',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('registro_id', sa.Integer(), nullable=False),
    sa.Column('sintoma_id', sa.String(length=10), nullable=False),
    sa.Column('intensidade', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['registro_id'], ['registros_diarios.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    
    with op.batch_alter_table('registros_diarios', schema=None) as batch_op:
        batch_op.add_column(sa.Column('observacoes', sa.Text(), nullable=True))
        batch_op.drop_column('localizacao_dor')
        batch_op.drop_column('intensidade_dor')
        batch_op.drop_column('qualidade_sono')
        batch_op.drop_column('nivel_fadiga')
        batch_op.drop_column('estado_emocional')

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('registros_diarios', schema=None) as batch_op:
        batch_op.add_column(sa.Column('estado_emocional', sa.VARCHAR(length=8), nullable=False))
        batch_op.add_column(sa.Column('nivel_fadiga', sa.INTEGER(), nullable=False))
        batch_op.add_column(sa.Column('qualidade_sono', sa.INTEGER(), nullable=False))
        batch_op.add_column(sa.Column('intensidade_dor', sa.INTEGER(), nullable=False))
        batch_op.add_column(sa.Column('localizacao_dor', sa.VARCHAR(), nullable=True))
        batch_op.drop_column('observacoes')

    op.drop_table('registro_sintomas')
    op.drop_table('registro_regioes_dor')
    # ### end Alembic commands ###