"""add profile fields to paciente

Revision ID: ae093c37a4ab
Revises: 2dd3ae881459
Create Date: 2026-01-28 08:54:23.864285

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'ae093c37a4ab'
down_revision: Union[str, Sequence[str], None] = '2dd3ae881459'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('pacientes', sa.Column('sexo', sa.String(length=50), nullable=True))
    op.add_column('pacientes', sa.Column('data_diagnostico', sa.DateTime(), nullable=True))
    op.add_column('pacientes', sa.Column('medicacoes', sa.Text(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('pacientes', 'medicacoes')
    op.drop_column('pacientes', 'data_diagnostico')
    op.drop_column('pacientes', 'sexo')
    # ### end Alembic commands ###
