"""update_registro_crise_model

Revision ID: fa36d9f4c0b6
Revises: ae093c37a4ab
Create Date: 2026-01-29 17:42:25.738273

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'fa36d9f4c0b6'
down_revision: Union[str, Sequence[str], None] = 'ae093c37a4ab'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('registros_crises', sa.Column('contexto', sa.Text(), nullable=False))
    op.drop_column('registros_crises', 'duracao')
    op.drop_column('registros_crises', 'audio_path')
    op.drop_column('registros_crises', 'texto_transcrito')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('registros_crises', sa.Column('texto_transcrito', sa.TEXT(), nullable=True))
    op.add_column('registros_crises', sa.Column('audio_path', sa.VARCHAR(), nullable=True))
    op.add_column('registros_crises', sa.Column('duracao', sa.VARCHAR(), nullable=False))
    op.drop_column('registros_crises', 'contexto')
    # ### end Alembic commands ###
